# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20170224_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
