# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20170220_1337'),
        ('user_management', '0004_auto_20170220_2038'),
    ]

    operations = [
    ]
