# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20170220_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='user_management.User'),
        ),
    ]
