# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_user_is_online'),
        ('user_management', '0005_user_friends'),
    ]

    operations = [
    ]
