# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_merge_20170221_0939'),
        ('chat', '0002_auto_20170222_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.MembershipInChat'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipinchat',
            unique_together=set([('chat_room', 'user')]),
        ),
    ]
