# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_user_is_online'),
        ('chat', '0003_auto_20170222_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershipinchat',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='membershipinchat',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='membershipinchat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='user_management.User'),
        ),
        migrations.DeleteModel(
            name='MembershipInChat',
        ),
    ]
