# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_user_is_online'),
        ('chat', '0004_auto_20170223_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_management.User'),
            preserve_default=False,
        ),
    ]
