# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_1', models.ManyToManyField(related_name='current_user', to='user_management.User')),
                ('user_id_2', models.ManyToManyField(related_name='friend', to='user_management.User')),
            ],
        ),
    ]
