# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
