# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_song_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
