# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_auto_20170220_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='music'),
        ),
    ]
